services:
  mysql:
    image: mysql:latest
    container_name: my_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: veterinaria
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - "mysql_db:/var/lib/mysql"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_db:
